redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://h:p54ae7355fdeaaf4f7f1e88a8c27e860bc4cf224253651b7ba65fb550ab4b7ff8@ec2-54-227-223-104.compute-1.amazonaws.com:64399
development: *redis
test: *redis

